name: ssl-multidomain

channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
 
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - pytorch-cuda=12.1
  - einops
  - jupyter
  - matplotlib
  - plotly
  - python-kaleido
  - pandas
  - tqdm=4.65
  - scipy
  - scikit-learn
  - numba=0.61
  - seaborn=0.13.2
  - umap-learn=0.5.4
  - tensorboard
  - ipdb
  - tabulate
  - scikit-image
  - wandb
  - datashader 
  - bokeh 
  - holoviews 
  - colorcet 