name: ssl-multidomain

channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
 
dependencies:
  - python=3.11
  - numpy
  - pytorch
  - pytorch-cuda=12.1
  - einops
  - jupyter
  - matplotlib
  - plotly
  - python-kaleido
  - pandas
  - tqdm=4.65
  - scipy
  - scikit-learn